apiVersion: apiextensions.k8s.io/v1beta1 
kind: CustomResourceDefinition
metadata:
  name: a-services.beta.jbcnconf.salaboy.com
spec:
  group: beta.jbcnconf.salaboy.com 
  version: v1 
  scope: Namespaced 
  names:
    plural: a-services
    singular: a-service
    kind: AService
    shortNames:
    - a
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            serviceName:
              type: string
          required:
            - serviceName