apiVersion: apiextensions.k8s.io/v1beta1 
kind: CustomResourceDefinition
metadata:
  name: applications.beta.k8s.salaboy.org
spec:
  group: beta.k8s.salaboy.org
  version: v1 
  scope: Namespaced 
  subresources:
    status: {}
  names:
    plural: applications 
    singular: application
    kind: Application 
    shortNames:
    - apps
  