apiVersion: apiextensions.k8s.io/v1beta1 
kind: CustomResourceDefinition
metadata:
  name: applications.beta.jbcnconf.salaboy.com
spec:
  group: beta.jbcnconf.salaboy.com
  version: v1 
  scope: Namespaced 
  names:
    plural: applications 
    singular: application
    kind: Application 
    shortNames:
    - apps
  