apiVersion: apiextensions.k8s.io/v1beta1 
kind: CustomResourceDefinition
metadata:
  name: service-bs.beta.k8s.salaboy.org
spec:
  group: beta.k8s.salaboy.org
  version: v1 
  scope: Namespaced 
  names:
    plural: service-bs
    singular: service-b
    kind: ServiceB
    shortNames:
    - b
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            serviceName:
              type: string
          required:
            - serviceName